name: Build/Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency: 
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      
      - name: Install Dependencies
        run: npm ci

      - name: Build Site
        run: npm run build
        env:
          API_KEY_GITHUB: ${{ secrets.API_KEY_GITHUB }}

      - name: Create Deployment Tarball
        uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: ./out
          files: .
          outPath: pictogrammers-${{ github.run_id }}.tar.gz

      - name: Upload Tarball Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pictogrammers-${{ github.run_id }}
          path: pictogrammers-${{ github.run_id }}.tar.gz

  deploy:
    needs: build
    name: Deploy Website
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Download Tarball Artifact
        uses: actions/download-artifact@v3
        with:
          name: pictogrammers-${{ github.run_id }}

      - name: Deploy Tarball to Server
        uses: trendyminds/github-actions-rsync@master
        with:
          RSYNC_OPTIONS: -avzr --delete
          RSYNC_TARGET: /opt/${{ secrets.SSH_USER }}/temp
          RSYNC_SOURCE: /pictogrammers-${{ github.run_id }}.tar.gz
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USER }}
          SSH_HOSTNAME: ${{ secrets.SSH_HOST }}

      - name: Expand Tarball
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            tar -zxf /opt/${{ secrets.SSH_USER }}/temp/pictogrammers-${{ github.run_id }}.tar.gz -C /opt/${{ secrets.SSH_USER }}/pictogrammers --recursive-unlink
            rm /opt/${{ secrets.SSH_USER }}/temp/pictogrammers-${{ github.run_id }}.tar.gz
